var namespace_interfaz_package =
[
    [ "AltaDiccionario", "class_interfaz_package_1_1_alta_diccionario.html", "class_interfaz_package_1_1_alta_diccionario" ],
    [ "AltaLectores", "class_interfaz_package_1_1_alta_lectores.html", "class_interfaz_package_1_1_alta_lectores" ],
    [ "AltaLibroLectura", "class_interfaz_package_1_1_alta_libro_lectura.html", "class_interfaz_package_1_1_alta_libro_lectura" ],
    [ "AltaLibroTexto", "class_interfaz_package_1_1_alta_libro_texto.html", "class_interfaz_package_1_1_alta_libro_texto" ],
    [ "BajaLector", "class_interfaz_package_1_1_baja_lector.html", "class_interfaz_package_1_1_baja_lector" ],
    [ "BajaLibro", "class_interfaz_package_1_1_baja_libro.html", "class_interfaz_package_1_1_baja_libro" ],
    [ "BusquedaFacturas", "class_interfaz_package_1_1_busqueda_facturas.html", "class_interfaz_package_1_1_busqueda_facturas" ],
    [ "BusquedaLector", "class_interfaz_package_1_1_busqueda_lector.html", "class_interfaz_package_1_1_busqueda_lector" ],
    [ "BusquedaLibro", "class_interfaz_package_1_1_busqueda_libro.html", "class_interfaz_package_1_1_busqueda_libro" ],
    [ "ComprarLector", "class_interfaz_package_1_1_comprar_lector.html", "class_interfaz_package_1_1_comprar_lector" ],
    [ "ComprarLibro", "class_interfaz_package_1_1_comprar_libro.html", "class_interfaz_package_1_1_comprar_libro" ],
    [ "ConsultaBusqueda", "class_interfaz_package_1_1_consulta_busqueda.html", "class_interfaz_package_1_1_consulta_busqueda" ],
    [ "ConsultaLector", "class_interfaz_package_1_1_consulta_lector.html", "class_interfaz_package_1_1_consulta_lector" ],
    [ "ConsultaLibro", "class_interfaz_package_1_1_consulta_libro.html", "class_interfaz_package_1_1_consulta_libro" ],
    [ "ConsultaLista", "class_interfaz_package_1_1_consulta_lista.html", "class_interfaz_package_1_1_consulta_lista" ],
    [ "ConsultaListaLectores", "class_interfaz_package_1_1_consulta_lista_lectores.html", "class_interfaz_package_1_1_consulta_lista_lectores" ],
    [ "facturas", "class_interfaz_package_1_1facturas.html", "class_interfaz_package_1_1facturas" ],
    [ "InformacionCliente", "class_interfaz_package_1_1_informacion_cliente.html", "class_interfaz_package_1_1_informacion_cliente" ],
    [ "InterfazAdmin", "class_interfaz_package_1_1_interfaz_admin.html", "class_interfaz_package_1_1_interfaz_admin" ],
    [ "InterfazAlta", "class_interfaz_package_1_1_interfaz_alta.html", "class_interfaz_package_1_1_interfaz_alta" ],
    [ "InterfazBaja", "class_interfaz_package_1_1_interfaz_baja.html", "class_interfaz_package_1_1_interfaz_baja" ],
    [ "InterfazCliente", "class_interfaz_package_1_1_interfaz_cliente.html", "class_interfaz_package_1_1_interfaz_cliente" ],
    [ "InterfazComprar", "class_interfaz_package_1_1_interfaz_comprar.html", "class_interfaz_package_1_1_interfaz_comprar" ],
    [ "InterfazConsulta", "class_interfaz_package_1_1_interfaz_consulta.html", "class_interfaz_package_1_1_interfaz_consulta" ],
    [ "InterfazConsultaFactura", "class_interfaz_package_1_1_interfaz_consulta_factura.html", "class_interfaz_package_1_1_interfaz_consulta_factura" ],
    [ "InterfazInicio", "class_interfaz_package_1_1_interfaz_inicio.html", "class_interfaz_package_1_1_interfaz_inicio" ],
    [ "InterfazRegistro", "class_interfaz_package_1_1_interfaz_registro.html", "class_interfaz_package_1_1_interfaz_registro" ],
    [ "ListaFacturas", "class_interfaz_package_1_1_lista_facturas.html", "class_interfaz_package_1_1_lista_facturas" ],
    [ "VerificarLector", "class_interfaz_package_1_1_verificar_lector.html", "class_interfaz_package_1_1_verificar_lector" ],
    [ "VerificarLibro", "class_interfaz_package_1_1_verificar_libro.html", "class_interfaz_package_1_1_verificar_libro" ]
];